apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-deploy-api-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy
  resources:
  - name: my-source-repo
    resourceRef:
      name: vote-api-repo
  - name: my-image-resource
    resourceRef:
      name: vote-api-image
  params:
  - name: deployment-name
    value: vote-api