---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: vote-cicd-listener
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: vote-cicd-triggers
#      interceptors:
#        - github:
#            secretRef:
#              secretName: foo
#              secretKey: bar
#            eventTypes:
#              - pull_request
      bindings:
        - name: vote-cicd-pipelinebinding
      template:
        name: vote-cicd-triggertemplate
